name: avaliacao_04
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  sqflite: ^2.3.2
  sqlite3: ^1.5.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
