name: seu_projeto
description: Formulário de validação em Flutter

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0  # Dependência para validação de data
  mask_text_input_formatter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
